import { ROOM_ASCII, getRoomAscii } from './ascii-art.js';

export const rooms = {
  Celda: {
    dirName: "Celda",
    displayName: "Celda",
    backlink: null,
    links: ["celda_cajon", "celda_armario", "celda_vitrina", "Pasillo"],
    files: ["nota_bienvenida.txt", "panel.exe"],
    perms: {
      read: true,
      write: true,
      execute: true,
    },
    asciiArt: ROOM_ASCII.CELDA,
  },
  Pasillo: {
    dirName: "Pasillo",
    displayName: "Pasillo",
    backlink: "Celda",
    lockmsg: "La puerta está cerrada. Parece que el panel lateral controla la apertura.",
    links: ["Laboratorio", "Almacen"],
    files: ["poster_1.psd", "poster_2.psd", "nota_de_personal.txt", "keypad.exe"],
    perms: {
      read: true,
      write: false,
      execute: false,
    },
    asciiArt: ROOM_ASCII.PASILLO,
  },
  celda_cajon: {
    dirName: "Celda\\cajon",
    displayName: "cajon",
    backlink: "Celda",
    links: [],
    files: ["calcetin_viejo.txt", "garabato.md"],
    perms: {
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.CELDA_CAJON,
  },
  celda_vitrina: {
    dirName: "Celda\\vitrina",
    displayName:"vitrina",
    backlink: "Celda",
    links: [],
    files: ["herramienta", "manual_usuario.pdf", "post_it.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.CELDA_VITRINA,
  },
  celda_armario: {
    dirName: "Celda\\armario",
    displayName:"armario",
    backlink: "Celda",
    links: ["celda_armario_caja"],
    files: ["uniforme.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.CELDA_ARMARIO,
  },
  celda_armario_caja: {
    dirName: "Celda\\armario\\caja",
    displayName: "caja",
    backlink: "celda_armario",
    links: [],
    files: [],
    perms: {
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.CELDA_ARMARIO_CAJA,
  },
  Laboratorio: {
    dirName: "Laboratorio",
    displayName:"Laboratorio",
    backlink: "Pasillo",
    lockmsg: "La puerta está cerrada. Necesito el código para abrirla.",
    links: ["lab_logs", "Servidores", "Control"],
    files: ["notas_de_investigacion.txt","consola.exe", "estatua.obj",],
    perms :{
      read: true,
      write: false,
      execute: false,
    },
    asciiArt: ROOM_ASCII.LABORATORIO,
  },
  Almacen: {
    dirName: "Almacen",
    displayName:"Almacen",
    backlink: "Pasillo",
    lockmsg: "La puerta está bloqueada. No parece haber forma de abrirla desde aquí.",
    links: ["Almacen_caja_1","Almacen_caja_2","Almacen_caja_3","Almacen_caja_4","Almacen_caja_5","Almacen_caja_6","Almacen_caja_7","Almacen_caja_8","Almacen_caja_9","Almacen_caja_10","Almacen_caja_11","Almacen_caja_12","Almacen_caja_13","Almacen_caja_14","Almacen_caja_15","Almacen_caja_16","Almacen_caja_17","Almacen_caja_18","Almacen_caja_19","Almacen_caja_20"],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: false,
    },
    asciiArt: ROOM_ASCII.ALMACEN,
  },
  Almacen_caja_1: {
    dirName: "Almacen\\caja_1",
    displayName:"caja_1",
    backlink: "Almacen",
    links: [],
    files: ["paquete_de_folios.zip","paquete_de_folios_abierto.zip"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_1,
  },
  Almacen_caja_2: {
    dirName: "Almacen\\caja_2",
    displayName:"caja_2",
    backlink: "Almacen",
    links: [],
    files: ["roca.stl", "trapo_sucio.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_2,
  },
  Almacen_caja_3: {
    dirName: "Almacen\\caja_3",
    displayName:"caja_3",
    backlink: "Almacen",
    links: [],
    files: ["calcetin_viejo.txt", "papel_desgastado.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_3,
  },
  Almacen_caja_4: {
    dirName: "Almacen\\caja_4",
    displayName:"caja_4",
    backlink: "Almacen",
    links: [],
    files: ["calcetin_viejo.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_4,
  },
  Almacen_caja_5: {
    dirName: "Almacen\\caja_5",
    displayName:"caja_5",
    backlink: "Almacen",
    links: [],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_5,
  },
  Almacen_caja_6: {
    dirName: "Almacen\\caja_6",
    displayName:"caja_6",
    backlink: "Almacen",
    links: [],
    files: ["herramienta", "manual_usuario.pdf", "herramienta_rota"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_6,
  },
  Almacen_caja_7: {
    dirName: "Almacen\\caja_7",
    displayName:"caja_7",
    backlink: "Almacen",
    links: [],
    files: ["papel_viejo.txt","admin.pub", "papel_desgastado.txt", "paquete_de_folios_abierto.zip"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_7,
  },
  Almacen_caja_8: {
    dirName: "Almacen\\caja_8",
    displayName:"caja_8",
    backlink: "Almacen",
    links: [],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_8,
  },
  Almacen_caja_9: {
    dirName: "Almacen\\caja_9",
    displayName:"caja_9",
    backlink: "Almacen",
    links: [],
    files: ["roca.stl", "herramienta_rota"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_9,
  },
  Almacen_caja_10: {
    dirName: "Almacen\\caja_10",
    displayName:"caja_10",
    backlink: "Almacen",
    links: [],
    files: ["trapo_sucio.txt", "papel_desgastado.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_10,
  },
  Almacen_caja_11: {
    dirName: "Almacen\\caja_11",
    displayName:"caja_11",
    backlink: "Almacen",
    links: [],
    files: ["paquete_de_folios.zip", "papel_desgastado.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_11,
  },
  Almacen_caja_12: {
    dirName: "Almacen\\caja_12",
    displayName:"caja_12",
    backlink: "Almacen",
    links: [],
    files: ["herramienta", "manual_usuario.pdf", "herramienta_rota"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_12,
  },
  Almacen_caja_13: {
    dirName: "Almacen\\caja_13",
    displayName:"caja_13",
    backlink: "Almacen",
    links: [],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_13,
  },
  Almacen_caja_14: {
    dirName: "Almacen\\caja_14",
    displayName:"caja_14",
    backlink: "Almacen",
    links: [],
    files: ["papel_viejo.txt", "papel_desgastado.txt", "paquete_de_folios_abierto.zip"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_14,
  },
  Almacen_caja_15: {
    dirName: "Almacen\\caja_15",
    displayName:"caja_15",
    backlink: "Almacen",
    links: [],
    files: ["tarjeta_seguridad.bin", "calcetin_viejo.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_15,
  },
  Almacen_caja_16: {
    dirName: "Almacen\\caja_16",
    displayName:"caja_16",
    backlink: "Almacen",
    links: [],
    files: ["roca.stl", "calcetin_viejo.txt", "papel_viejo.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_16,
  },
  Almacen_caja_17: {
    dirName: "Almacen\\caja_17",
    displayName:"caja_17",
    backlink: "Almacen",
    links: [],
    files: ["paquete_de_folios_abierto.zip", "herramienta_rota"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_17,
  },
  Almacen_caja_18: {
    dirName: "Almacen\\caja_18",
    displayName:"caja_18",
    backlink: "Almacen",
    links: [],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_18,
  },
  Almacen_caja_19: {
    dirName: "Almacen\\caja_19",
    displayName:"caja_19",
    backlink: "Almacen",
    links: [],
    files: ["roca.stl", "herramienta", "herramienta_rota"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_19,
  },
  Almacen_caja_20: {
    dirName: "Almacen\\caja_20",
    displayName:"caja_20",
    backlink: "Almacen",
    links: [],
    files: ["roca.stl", "manual_usuario.pdf", "papel_desgastado.txt"],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.ALMACEN_CAJA_20,
  },
  Control: {
    dirName: "Control",
    displayName:"Control",
    backlink: "Laboratorio",
    links: ["Salida"],
    files: ["escaner_de_retina.exe", "nota_seguridad.txt"],
    perms :{
      read: true,
      write: false,
      execute: false,
    },
    asciiArt: ROOM_ASCII.CONTROL,  
  },
  lab_logs: {
    dirName: "Laboratorio\\server_logs",
    displayName:"server_logs",
    backlink: "Laboratorio",
    links: [],
    files: [],
    perms :{
      read: true,
      write: false,
      execute: true,
    },
    asciiArt: ROOM_ASCII.LAB_LOGS,
  },
  Servidores: {
  dirName: "Servidores",
  displayName:"Servidores",
  backlink: "Laboratorio",
  links: [],
  files: [".servidor_1.bat",".servidor_2.bat",".servidor_3.bat",".servidor_4.bat", ".nota_borrosa.md"],
  perms :{
    read: true,
    write: false,
    execute: false,
  },
  asciiArt: ROOM_ASCII.SERVIDORES,
  },
  Salida: {
  dirName: "Salida",
  displayName:"Salida",
  backlink: "Control",
  links: [],
  files: [],
  perms :{
    read: false,
    write: false,
    execute: false,
  },
  asciiArt: ROOM_ASCII.SALIDA,
  },
};